[package]
name = "RustStuff"
version = "0.1.0"
authors = ["ubarilan <ubarilan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.6.0"
rpassword = "5.0.1"
path-absolutize = "3.0.10"